[project]
name = "my-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp-cors>=0.8.0",
    "aiohttp[speedups]>=3.11.13",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "requests>=2.32.3",
]
