name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Minimize uv cache
        run: uv cache prune --ci

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest tests
